const aiTools = [
  { id: 'elevenlabs', name: 'ElevenLabs', short: 'EL', category: 'Voice / Audio', rating: 5, description: 'Natural-sounding AI voice generation for narration, dubbing and audio projects.', bestFor: 'Voiceovers, podcasts, localization and creator audio.', free: 'Free access is available with usage limits.', url: 'https://elevenlabs.io/' },
  { id: 'capcut', name: 'CapCut', short: 'CC', category: 'Video / Editing', rating: 4, description: 'Creator-focused video editing with captions, effects and AI-assisted tools.', bestFor: 'Short-form video, captions and social content.', free: 'A free version is available; some features require a paid plan.', url: 'https://www.capcut.com/' },
  { id: 'canva', name: 'Canva', short: 'CA', category: 'Images / Design', rating: 4, description: 'Fast visual design for presentations, social graphics, documents and campaigns.', bestFor: 'Everyday design, thumbnails and brand content.', free: 'A free plan is available, with premium content and features on paid plans.', url: 'https://www.canva.com/' },
  { id: 'chatgpt', name: 'ChatGPT', short: 'CG', category: 'Writing / Assistant', rating: 5, description: 'General-purpose AI assistant for writing, analysis, ideas, research and coding.', bestFor: 'Brainstorming, drafting, learning and everyday problem solving.', free: 'A free plan is available, with expanded access on paid plans.', url: 'https://chatgpt.com/' },
  { id: 'claude', name: 'Claude', short: 'CL', category: 'Writing / Assistant', rating: 5, description: 'Thoughtful AI assistant for writing, analysis, long documents and complex tasks.', bestFor: 'Long-form work, research, reasoning and coding.', free: 'Free access is available with usage limits.', url: 'https://claude.ai/' },
  { id: 'perplexity', name: 'Perplexity', short: 'PX', category: 'Research / Search', rating: 4, description: 'AI-powered search that helps explore questions with source-backed answers.', bestFor: 'Research, comparisons, fact-finding and discovery.', free: 'A free plan is available with limits on advanced features.', url: 'https://www.perplexity.ai/' },
  { id: 'leonardo', name: 'Leonardo AI', short: 'LA', category: 'Images / Design', rating: 4, description: 'Flexible AI image creation with controls for concepts, assets and product visuals.', bestFor: 'Artwork, game assets, product images and concept design.', free: 'A free tier with generation limits is available.', url: 'https://leonardo.ai/' },
  { id: 'ideogram', name: 'Ideogram', short: 'ID', category: 'Images / Typography', rating: 4, description: 'AI image generation for graphics, illustrations, posters and visual concepts.', bestFor: 'Typography-led graphics, posters, social visuals and branding ideas.', free: 'A free tier is available with generation limits.', url: 'https://ideogram.ai/' },
  { id: 'runway', name: 'Runway', short: 'RW', category: 'Video / Generation', rating: 4, description: 'Creative AI workspace for generating, editing and extending video.', bestFor: 'AI video, visual effects, concept clips and motion experiments.', free: 'Free access is available with limited credits and features.', url: 'https://runway.com/' },
  { id: 'descript', name: 'Descript', short: 'DS', category: 'Audio / Video Editing', rating: 4, description: 'Video and audio editing built around an editable transcript.', bestFor: 'Podcasts, interviews, tutorials, captions and spoken-word video.', free: 'A free plan is available with limited usage.', url: 'https://www.descript.com/' },
  { id: 'midjourney', name: 'Midjourney', short: 'MJ', category: 'Images / Art', rating: 5, description: 'Distinctive AI image generation for imaginative, art-directed visual concepts.', bestFor: 'Concept art, moodboards, stylized visuals and creative exploration.', free: 'Access and trial availability can change; check current plans before starting.', url: 'https://www.midjourney.com/' },
  { id: 'firefly', name: 'Adobe Firefly', short: 'AF', category: 'Images / Creative Suite', rating: 4, description: 'Adobe’s generative AI tools for creating and editing visual content.', bestFor: 'Design workflows, image generation and Adobe-based creative work.', free: 'Free generative credits are available; paid plans expand access.', url: 'https://www.adobe.com/products/firefly.html' },
  { id: 'notion-ai', name: 'Notion AI', short: 'NA', category: 'Productivity / Writing', rating: 4, description: 'AI built into Notion for writing, workspace search, notes and team workflows.', bestFor: 'Project docs, knowledge bases, meeting notes and planning.', free: 'Limited trial access is available; broader AI access depends on the Notion plan.', url: 'https://www.notion.com/product/ai' },
  { id: 'grammarly', name: 'Grammarly', short: 'GR', category: 'Writing / Communication', rating: 4, description: 'Writing assistance for clarity, tone, rewrites and polished communication.', bestFor: 'Emails, documents, professional writing and tone refinement.', free: 'A free plan is available, with more AI and rewrite tools on paid plans.', url: 'https://www.grammarly.com/' },
  { id: 'jasper', name: 'Jasper', short: 'JA', category: 'Marketing / Writing', rating: 4, description: 'AI workspace focused on on-brand marketing content and campaign workflows.', bestFor: 'Marketing teams, brand voice, campaign content and content operations.', free: 'A trial is available; ongoing access is through paid plans.', url: 'https://www.jasper.ai/' },
  { id: 'synthesia', name: 'Synthesia', short: 'SY', category: 'Video / Avatars', rating: 4, description: 'AI video creation with avatars, voiceovers, localization and business templates.', bestFor: 'Training, explainers, onboarding and multilingual business video.', free: 'A free plan is available with defined limits.', url: 'https://www.synthesia.io/' },
  { id: 'heygen', name: 'HeyGen', short: 'HG', category: 'Video / Avatars', rating: 4, description: 'Text-to-video creation with AI presenters, voiceovers and localization tools.', bestFor: 'Presenter-led explainers, product updates and global video content.', free: 'A free tier is available; usage limits apply.', url: 'https://www.heygen.com/' },
  { id: 'pika', name: 'Pika', short: 'PK', category: 'Video / Generation', rating: 4, description: 'Prompt-driven creative video generation for playful motion and quick experiments.', bestFor: 'Short AI clips, social concepts and visual experimentation.', free: 'Free credits are available; additional usage is offered through paid plans.', url: 'https://pika.art/' },
  { id: 'veed', name: 'VEED', short: 'VE', category: 'Video / Editing', rating: 4, description: 'Online video editor with AI-assisted captions, cleanup and content creation.', bestFor: 'Social video, product demos, subtitles and quick team edits.', free: 'A free plan is available with feature and export limits.', url: 'https://www.veed.io/' },
  { id: 'otter', name: 'Otter.ai', short: 'OT', category: 'Meetings / Transcription', rating: 4, description: 'AI meeting notes with live transcription, summaries and searchable conversations.', bestFor: 'Meeting capture, transcripts, summaries and follow-up notes.', free: 'A free plan is available with usage limits.', url: 'https://otter.ai/' }
];

window.aiTools = aiTools;
